# Directory Air watches (current dir)
root = "."
# Folder with test data (Air ignores this)
testdata_dir = "testdata"
# Where Air puts the compiled binary
tmp_dir = "tmp"

# How Air builds the app
[build]
  # Path where teh compiled app goes
  bin = "./tmp/main"
  # CLI arguments to pass to the app (none)
  args_bin = []
  # Build command
  # -mod=mod ignores the local vendor directory (if any)
  cmd = "go build -mod=mod -o ./tmp/main cmd/server/main.go"
  # Wait 1000ms (1 sec) after  file changes before rebuilding
  delay = 1000
  # Don't rerun binary
  rerun = false
  # Wait 5000m before restarting after a build
  rerun_delay = 500
  # How long to wait before force-killing the old app (immediate)
  kill_delay = "0s"
  # File types that trigger rebuilds
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  # Specific folders to watch (empty = all)
  include_dir = []
  # Specific files to watch (empty = all)
  include_file = []
  # Directories to ignore
  # tmp: where Air puts builds (don't watch that output)
  # vendor: dependencies (don't rebuild when these change)
  # .git: don't rebuild on git changes
  exclude_dir = ["assets", "tmp", "vendor", "deployments", "examples", "scripts", "testdata", "migrations", ".git"]
  # Files to ignore
  exclude_file = ["compose.yaml"]
  # Ignore test files
  exclude_regex = ["_test.go"]
  # Watch all files, even if unchanged
  exclude_unchanged = false
  # Don't follow symlinks
  follow_symlink = false
  # Custom command to run instead of just the binary
  full_bin = ""
  # Use system file events instead of polling
  poll = false
  # How often to check for changes if polling (0 = use events)
  poll_interval = 0
  # Send interrupt signal to stop app (false = just kill the app)
  send_interrupt = false
  # Stop if running as root user
  stop_on_root = false
  # Where to save build error messages
  log = "build-errors.log"

# Color output
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

# What gets logged
[log]
  # Show all logs, not just main app ogs
  main_only = false
  # Don't add timestamps to log messages
  time = false

[misc]
  # Don't delete tmp files when Air stops
  clean_on_exit = false
